executor: "KubernetesExecutor"

env:
  - name: AIRFLOW__CORE__LOAD_EXAMPLES
    value: "False"
  - name: AIRFLOW_CONN_KUBERNETES_DEFAULT
    value: '{"conn_type": "kubernetes", "extra": {"in_cluster": true}}'

extraPipPackages:
  - "apache-airflow-providers-apache-spark[cncf.kubernetes]"

webserverSecretKeySecretName: airflow-webserver-secret

postgresql:
  enabled: true

web:
  service:
    type: NodePort
    nodePort: 30080

dags:
  persistence:
    enabled: true
    existingClaim: ""
  gitSync:
    enabled: false
